name: dental_hero
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  ar_flutter_plugin: ^0.7.3
  arcore_flutter_plugin: ^0.1.0
  bulleted_list: ^0.0.1+0.1a
  cloud_firestore: ^4.8.5
  confetti: ^0.7.0
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_bloc: ^8.1.3
  flutter_inset_box_shadow: ^1.0.8
  flutter_native_splash: ^2.2.19
  get_it: ^7.6.0
  google_fonts: ^4.0.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  path_provider: ^2.1.1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.1
  syncfusion_flutter_charts: ^23.1.36
  timeline_tile: ^2.0.0
  vector_math: ^2.1.4
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/
    - assets/models/
