name: dental_hero
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  arcore_flutter_plugin: ^0.1.0
  bloc: ^8.1.2
  cloud_firestore: ^4.8.5
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_inset_box_shadow: ^1.0.8
  flutter_native_splash: ^2.3.2
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_color: "#e2eeff"
  background_image: assets/images/splash.png
  image: assets/images/logo_full.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/
